"""empty message

Revision ID: 1b9eee4a33bd
Revises: 1bc2e9181ee0
Create Date: 2023-10-18 17:10:29.157193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b9eee4a33bd'
down_revision = '1bc2e9181ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kinship',
    sa.Column('kid_id', sa.Integer(), nullable=True),
    sa.Column('mother_id', sa.Integer(), nullable=True),
    sa.Column('father_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['father_id'], ['animal.id'], ),
    sa.ForeignKeyConstraint(['kid_id'], ['animal.id'], ),
    sa.ForeignKeyConstraint(['mother_id'], ['animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('origin', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('animal_type', sa.Enum('Cow', 'Bull', 'Heifer', 'Calf', name='animaltype'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_column('animal_type')
        batch_op.drop_column('origin')
        batch_op.drop_column('birth_date')

    op.drop_table('kinship')
    # ### end Alembic commands ###
