"""empty message

Revision ID: 516565312a20
Revises: 9380acd18ef7
Create Date: 2023-12-18 20:34:30.679155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516565312a20'
down_revision = '9380acd18ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('animal_type',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('Vaca', 'Boi', 'Novilha', 'Bezerro', name='animaltype'),
               existing_nullable=True)
        batch_op.alter_column('animal_sex',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('Macho', 'Femea', name='animalsex'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('animal_sex',
               existing_type=sa.Enum('Macho', 'Femea', name='animalsex'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)
        batch_op.alter_column('animal_type',
               existing_type=sa.Enum('Vaca', 'Boi', 'Novilha', 'Bezerro', name='animaltype'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)

    # ### end Alembic commands ###
