"""Initial migration for Cows model

Revision ID: 888a1a78542f
Revises: d2da61fd3362
Create Date: 2023-07-13 20:06:41.381995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888a1a78542f'
down_revision = 'd2da61fd3362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cow')
    # ### end Alembic commands ###
