"""empty message

Revision ID: 9380acd18ef7
Revises: f4ce36850eb2
Create Date: 2023-11-09 17:17:01.959375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9380acd18ef7'
down_revision = 'f4ce36850eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('animal_sex', sa.Enum('Male', 'Female', name='animalsex'), nullable=True))
        batch_op.alter_column('animal_type',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('animal_type',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
        batch_op.drop_column('animal_sex')

    # ### end Alembic commands ###
